### ISSUE TITLE
Does not find config file

### ISSUE THREAD

**Issue by weswitt** [xx4h/hctl#21]
On windows HCTL only finds the config file if it is located in the current directory. It should look for the config file in the same directory as the HCTL.EXE file. Then I can have HCTL in a tools dir that is on my path and it will always work.  The INIT command creates a config file located in c:\Users\myuser\.config\hctl\hctl.yaml, but it will never look there to find it.

**Comment by xx4h** [comment]
Thanks for reporting!

So i guess it makes sense to have 3 locations in the following order:
1. Current working directory
2. Default config path (`~/.config/hctl/hctl.yaml` on Linux, `C:\Users\USER\.config\hctl\hctl.yaml`)
3. Directory where the binary is located

>  The INIT command creates a config file located in c:\Users\myuser.config\hctl\hctl.yaml, but it will never look there to find it.
Is it really `c:\Users\myuser.config\...` or is it `c:\Users\myuser\.config\...` (which it is in my test)?
