### ISSUE TITLE
init wizard URI assist (add /api if missing)

### ISSUE THREAD

**Issue by reedstrm** [xx4h/hctl#22]
For those who want to try this out, but don't read all the instructions, it's likely thata a lot of people will do what I did, and just type in their homeassistant hostname, rather than the full API URI. Then they will get the fun error message:

```
 hctl list
3:38PM ERR Could not create Services Object: invalid character ':' after top-level value
States
```
Turning up log level to INFO showed it trying to fetch <hostname>/states, which 404s.

So, two feature enhancements -
 1. Better error on a 404 for a bad URI (I think you've got a generic "better errors" issue for that already)
 2. Some smarts in the init wizard to expect a uri ending in /api, and either error, or just go ahead and add it. Might even want to do a quick fetch/test to see if you get a 404 or a 401 (and maybe test after you get the token as well?)

**Comment by xx4h** [comment]
Hi there, thanks for the feedback!

> 1. Better error on a 404 for a bad URI (I think you've got a generic "better errors" issue for that already)

Agreed, the current error is not very helpful

> Some smarts in the init wizard to expect a uri ending in /api, and either error, or just go ahead and add it. Might even want to do a quick fetch/test to see if you get a 404 or a 401 (and maybe test after you get the token as well?)

I was thinking about this at the beginning, but wasn't happy with just checking `/api`. I think actually testing the root endpoint is the way to go, as it should return:
```
{"message":"API running."}
```
This way we directly check if we have a working token and correct url to the API
